builders:
  my_builder:
    import: "package:collection_gen/collection_gen.dart"
    builder_factories: ["collectionBuilder"]
    build_extensions:
      "$lib$": [".g.dart"]
    auto_apply: dependents
    build_to: source
